Implement in associate page and patient bill
Jagriti-InnoHealth-Platforms/ebloodbanking pull request #6
Opened 2023-05-04 11:07 UTC by Prasadmajji001

Modified two scripts 

The test run might fail because all the existing scripts are for dev8.

2023-05-04 12:07 UTC, jagritiinnohealth requested changes

2023-05-04 12:07 UTC, jagritiinnohealth commented on src/main/java/com/jagriti/plasma/pages/collection/associate/AddNewAssociatePage.java
> +    public SelenideElement associateAddedAlert = $("div[class*='messages']");
Why are you checking for alert messages instead of name values after save?

2023-05-04 12:19 UTC, Prasadmajji001 commented on src/main/java/com/jagriti/plasma/pages/collection/associate/AddNewAssociatePage.java
> +    public SelenideElement associateAddedAlert = $("div[class*='messages']");
Fixed and pushed

2023-05-05 04:56 UTC, jagritiinnohealth approved these changes

2023-05-05 04:56 UTC, merged